"""Credential-gated rainfall source adapters."""

from .imd import ImdAccessRestrictedError, ImdClient, SourceDisabledError
from .imerg import (
    IMERG_POLICIES,
    ImergCellAccumulation,
    ImergGridCellObservation,
    ImergRun,
    accumulate_imerg_cell,
    parse_imerg_observations,
    prepare_imerg_zonal_join,
)
from .imerg_client import (
    EARTHDATA_REGISTRATION_URL,
    GES_DISC_BASE,
    ImergAuthError,
    ImergClient,
    ImergCredentialsMissing,
    ImergDownload,
    ImergGranule,
    discover_granules,
    granule_for,
)
from .provenance import (
    GeometryReference,
    GeometryReviewRequired,
    SourceRevision,
    write_immutable_revision,
)
from .zonal import (
    IMERG_CELL_DEGREES,
    ZONAL_FORBIDS,
    ZONAL_PERMITS,
    BoundaryGradeError,
    CellWeight,
    CoverageError,
    MeasuredBoundary,
    ZonalAccumulation,
    ZonalWeights,
    aggregate_over_circle,
    cell_weights,
    grid_cell_id,
    load_measured_boundaries,
)

__all__ = [
    "EARTHDATA_REGISTRATION_URL",
    "GES_DISC_BASE",
    "IMERG_CELL_DEGREES",
    "IMERG_POLICIES",
    "ZONAL_FORBIDS",
    "ZONAL_PERMITS",
    "BoundaryGradeError",
    "CellWeight",
    "CoverageError",
    "GeometryReference",
    "GeometryReviewRequired",
    "ImdAccessRestrictedError",
    "ImdClient",
    "ImergAuthError",
    "ImergCellAccumulation",
    "ImergClient",
    "ImergCredentialsMissing",
    "ImergDownload",
    "ImergGranule",
    "ImergGridCellObservation",
    "ImergRun",
    "MeasuredBoundary",
    "SourceDisabledError",
    "SourceRevision",
    "ZonalAccumulation",
    "ZonalWeights",
    "accumulate_imerg_cell",
    "aggregate_over_circle",
    "cell_weights",
    "discover_granules",
    "granule_for",
    "grid_cell_id",
    "load_measured_boundaries",
    "parse_imerg_observations",
    "prepare_imerg_zonal_join",
    "write_immutable_revision",
]
